version: "3.9"

services:
  telegram-bot:
    image: ghcr.io/k54lid/downtify:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./k54lid-Downtify:/app/storage
    environment:
      TELEGRAM_BOT_TOKEN: "7307072659:AAEaD2TRGfxHTB70Yrk7Fqz1fAxeJfXK7Ss"
      WHITELISTED_IDS: "55"
      ADMIN_ID: "528269003"
      TELEGRAM_API_ROOT: "http://127.0.0.1:8081"
      TELEGRAM_WEBHOOK_PORT: "8443"
      TELEGRAM_WEBHOOK_URL: "http://127.0.0.1:8443"
      YTDL_AUTOUPDATE: "true"
      OPENAI_API_KEY: ""

  telegram-bot-api:
    image: ghcr.io/bots-house/docker-telegram-bot-api:latest
    network_mode: host
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "1898255"
      TELEGRAM_API_HASH: "4d2b63ef4b50c08bae36d136309159cc"
    command:
      - --dir=/var/lib/telegram-bot-api
      - --local
    volumes:
      - server-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081

volumes:
  server-data:
    driver: local
