

services:
  telegram-bot:
    image: ghcr.io/k54lid/downtify:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./k54lid-downtify:/app/storage
    environment:
      # get your bot token from @BotFather
      TELEGRAM_BOT_TOKEN: "7307072659:AAEaD2TRGfxHTB70Yrk7Fqz1fAxeJfXK7Ss"

      # comma separated list of telegram user ids, leave empty to allow all users
      WHITELISTED_IDS: ""

      # admin user id
      ADMIN_ID: "528269003"

      TELEGRAM_API_ROOT: "http://127.0.0.1:8081"
      TELEGRAM_WEBHOOK_PORT: "8443"
      TELEGRAM_WEBHOOK_URL: "http://127.0.0.1:8443"

      # whether to automatically update yt-dlp
      # defaults to "true", set to "false" to disable
      YTDL_AUTOUPDATE: "true"

      # provide your OpenAI API key to enable auto-translation (optional)
      OPENAI_API_KEY: ""

  telegram-bot-api:
    image: ghcr.io/bots-house/docker-telegram-bot-api:latest
    network_mode: host
    restart: unless-stopped
    environment:
      # get these values from https://core.telegram.org/api/obtaining_api_id
      TELEGRAM_API_ID: "1898255"
      TELEGRAM_API_HASH: "4d2b63ef4b50c08bae36d136309159cc"
    command:
      - --dir=/var/lib/telegram-bot-api
      #- --verbosity=2
      - --local
    volumes:
      - server-data:/var/lib/telegram-bot-api
    ports:
      - 8081:8081

volumes:
  server-data:
    driver: local
